"""Initial schema with users, leads, searches, exports, pipelines

Revision ID: 87e592885f04
Revises: 
Create Date: 2026-01-08 06:07:27.928450+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '87e592885f04'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('subscription_tier', sa.Enum('FREE', 'PRO', 'TEAM', 'ENTERPRISE', name='subscriptiontier'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('api_keys', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('usage_stats', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('exports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_url', sa.String(length=1000), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('format', sa.Enum('CSV', 'EXCEL', 'JSON', 'PDF', name='exportformat'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'EXPIRED', name='exportstatus'), nullable=False),
    sa.Column('records_count', sa.Integer(), nullable=False),
    sa.Column('filters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('columns', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('downloaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('download_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exports_created_at'), 'exports', ['created_at'], unique=False)
    op.create_index(op.f('ix_exports_expires_at'), 'exports', ['expires_at'], unique=False)
    op.create_index(op.f('ix_exports_format'), 'exports', ['format'], unique=False)
    op.create_index(op.f('ix_exports_id'), 'exports', ['id'], unique=False)
    op.create_index(op.f('ix_exports_status'), 'exports', ['status'], unique=False)
    op.create_index(op.f('ix_exports_user_id'), 'exports', ['user_id'], unique=False)
    op.create_table('leads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('company_hq', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('twitter_url', sa.String(length=500), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('propensity_score', sa.Integer(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('priority_tier', sa.String(length=20), nullable=True),
    sa.Column('recent_publication', sa.Boolean(), nullable=True),
    sa.Column('publication_year', sa.Integer(), nullable=True),
    sa.Column('publication_title', sa.Text(), nullable=True),
    sa.Column('publication_count', sa.Integer(), nullable=True),
    sa.Column('company_funding', sa.String(length=50), nullable=True),
    sa.Column('company_size', sa.String(length=50), nullable=True),
    sa.Column('uses_3d_models', sa.Boolean(), nullable=True),
    sa.Column('data_sources', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('enrichment_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('custom_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('last_contacted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_company'), 'leads', ['company'], unique=False)
    op.create_index(op.f('ix_leads_created_at'), 'leads', ['created_at'], unique=False)
    op.create_index(op.f('ix_leads_email'), 'leads', ['email'], unique=False)
    op.create_index(op.f('ix_leads_id'), 'leads', ['id'], unique=False)
    op.create_index(op.f('ix_leads_name'), 'leads', ['name'], unique=False)
    op.create_index(op.f('ix_leads_propensity_score'), 'leads', ['propensity_score'], unique=False)
    op.create_index(op.f('ix_leads_rank'), 'leads', ['rank'], unique=False)
    op.create_index(op.f('ix_leads_status'), 'leads', ['status'], unique=False)
    op.create_index(op.f('ix_leads_title'), 'leads', ['title'], unique=False)
    op.create_index(op.f('ix_leads_user_id'), 'leads', ['user_id'], unique=False)
    op.create_table('pipelines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('schedule', sa.Enum('MANUAL', 'DAILY', 'WEEKLY', 'MONTHLY', 'CUSTOM', name='pipelineschedule'), nullable=False),
    sa.Column('cron_expression', sa.String(length=100), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'DISABLED', 'RUNNING', 'ERROR', name='pipelinestatus'), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_run_status', sa.String(length=50), nullable=True),
    sa.Column('last_run_results', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('run_count', sa.Integer(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('total_leads_generated', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipelines_created_at'), 'pipelines', ['created_at'], unique=False)
    op.create_index(op.f('ix_pipelines_id'), 'pipelines', ['id'], unique=False)
    op.create_index(op.f('ix_pipelines_last_run_at'), 'pipelines', ['last_run_at'], unique=False)
    op.create_index(op.f('ix_pipelines_next_run_at'), 'pipelines', ['next_run_at'], unique=False)
    op.create_index(op.f('ix_pipelines_schedule'), 'pipelines', ['schedule'], unique=False)
    op.create_index(op.f('ix_pipelines_status'), 'pipelines', ['status'], unique=False)
    op.create_index(op.f('ix_pipelines_user_id'), 'pipelines', ['user_id'], unique=False)
    op.create_table('searches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('search_type', sa.String(length=50), nullable=False),
    sa.Column('filters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('results_count', sa.Integer(), nullable=False),
    sa.Column('results_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_saved', sa.Boolean(), nullable=False),
    sa.Column('saved_name', sa.String(length=255), nullable=True),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_searches_created_at'), 'searches', ['created_at'], unique=False)
    op.create_index(op.f('ix_searches_id'), 'searches', ['id'], unique=False)
    op.create_index(op.f('ix_searches_is_saved'), 'searches', ['is_saved'], unique=False)
    op.create_index(op.f('ix_searches_search_type'), 'searches', ['search_type'], unique=False)
    op.create_index(op.f('ix_searches_user_id'), 'searches', ['user_id'], unique=False)
    op.drop_table('biotech-leads-db')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('biotech-leads-db',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='biotech-leads-db_pkey')
    )
    op.drop_index(op.f('ix_searches_user_id'), table_name='searches')
    op.drop_index(op.f('ix_searches_search_type'), table_name='searches')
    op.drop_index(op.f('ix_searches_is_saved'), table_name='searches')
    op.drop_index(op.f('ix_searches_id'), table_name='searches')
    op.drop_index(op.f('ix_searches_created_at'), table_name='searches')
    op.drop_table('searches')
    op.drop_index(op.f('ix_pipelines_user_id'), table_name='pipelines')
    op.drop_index(op.f('ix_pipelines_status'), table_name='pipelines')
    op.drop_index(op.f('ix_pipelines_schedule'), table_name='pipelines')
    op.drop_index(op.f('ix_pipelines_next_run_at'), table_name='pipelines')
    op.drop_index(op.f('ix_pipelines_last_run_at'), table_name='pipelines')
    op.drop_index(op.f('ix_pipelines_id'), table_name='pipelines')
    op.drop_index(op.f('ix_pipelines_created_at'), table_name='pipelines')
    op.drop_table('pipelines')
    op.drop_index(op.f('ix_leads_user_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_title'), table_name='leads')
    op.drop_index(op.f('ix_leads_status'), table_name='leads')
    op.drop_index(op.f('ix_leads_rank'), table_name='leads')
    op.drop_index(op.f('ix_leads_propensity_score'), table_name='leads')
    op.drop_index(op.f('ix_leads_name'), table_name='leads')
    op.drop_index(op.f('ix_leads_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_email'), table_name='leads')
    op.drop_index(op.f('ix_leads_created_at'), table_name='leads')
    op.drop_index(op.f('ix_leads_company'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_exports_user_id'), table_name='exports')
    op.drop_index(op.f('ix_exports_status'), table_name='exports')
    op.drop_index(op.f('ix_exports_id'), table_name='exports')
    op.drop_index(op.f('ix_exports_format'), table_name='exports')
    op.drop_index(op.f('ix_exports_expires_at'), table_name='exports')
    op.drop_index(op.f('ix_exports_created_at'), table_name='exports')
    op.drop_table('exports')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
