import streamlit as st
import pandas as pd
import datetime

st.caption(f"Last updated: {datetime.datetime.now().isoformat()}")

st.set_page_config(
    page_title="AI Lead Scoring Dashboard",
    layout="wide"
)

GOOGLE_SHEET_CSV_URL = (
    "https://docs.google.com/spreadsheets/d/"
    "1uFhqrL8Qs0pz6UUO6Fcs04I1DmqOsDunxe9JpGrQx2g/export?format=csv"
)

@st.cache_data(ttl=60)
def load_data():
    df = pd.read_csv(GOOGLE_SHEET_CSV_URL)

    df.columns = (
        df.columns
          .str.strip()
          .str.lower()
          .str.replace(" ", "_")
    )

    return df

df = load_data()

# 🛑 Schema validation
required_columns = {"name", "propensity_score"}
missing = required_columns - set(df.columns)

if missing:
    st.error(f"Missing required columns: {missing}")
    st.stop()

st.title("AI Lead Scoring Dashboard")
st.markdown("""
This app presents ranked biotech/pharma leads based on explainable,
business-oriented scoring. Scores are derived from:
- Role fit
- Scientific research intent
- Funding stage
- Geographic relevance

Generated outputs are reproducible via the linked Google Sheet.
""")

st.sidebar.header("Filters")

min_score = st.sidebar.slider(
    "Minimum Propensity Score",
    min_value=0,
    max_value=100,
    value=50
)

filtered_df = df[df["propensity_score"] >= min_score]

st.subheader("Ranked Leads")

display_columns = [
    col for col in [
        "name",
        "title",
        "company",
        "person_location",
        "company_hq",
        "propensity_score"
    ]
    if col in df.columns
]

st.dataframe(
    filtered_df[display_columns]
        .sort_values("propensity_score", ascending=False),
    use_container_width=True
)

st.subheader("Score Breakdown")

if "score_breakdown" in df.columns:
    selected_name = st.selectbox(
        "Select a lead",
        filtered_df["name"].unique()
    )

    selected_row = filtered_df[
        filtered_df["name"] == selected_name
    ].iloc[0]

    st.json(selected_row["score_breakdown"])

st.markdown("---")
st.markdown("Generated by `AI Lead Scoring Pipeline` • Version 1.0")
