import streamlit as st
import pandas as pd
import datetime

st.caption("Data sourced from programmatically generated Google Sheet output.")

st.set_page_config(
    page_title="AI Lead Scoring Dashboard",
    layout="wide"
)

GOOGLE_SHEET_CSV_URL = (
    "https://docs.google.com/spreadsheets/d/"
    "1uFhqrL8Qs0pz6UUO6Fcs04I1DmqOsDunxe9JpGrQx2g/export?format=csv"
)

@st.cache_data(ttl=60)
def load_data():
    df = pd.read_csv(GOOGLE_SHEET_CSV_URL)

    df.columns = (
        df.columns
          .str.strip()
          .str.lower()
          .str.replace(" ", "_")
    )

    return df

df = load_data()

# 🛑 Schema validation
required_columns = {"name", "propensity_score"}
missing = required_columns - set(df.columns)

if missing:
    st.error(f"Missing required columns: {missing}")
    st.stop()

st.title("AI Lead Scoring Dashboard")
st.markdown("""
This app displays scored biotech/pharma leads ranked by relevance
to 3D in-vitro safety and toxicity models.
""")

st.sidebar.header("Filters")

min_score = st.sidebar.slider(
    "Minimum Score", 0, 100, 40
)
filtered = df[df["propensity_score"] >= min_score]


st.subheader("Ranked Leads")

display_columns = [
    col for col in [
        "name",
        "title",
        "company",
        "person_location",
        "company_hq",
        "propensity_score"
    ]
    if col in df.columns
]

st.dataframe(
    df.sort_values("propensity_score", ascending=False),
    use_container_width=True
)

st.subheader("Score Breakdown")

if "score_breakdown" in df.columns:
    selected = st.selectbox(
    "Select Lead for Breakdown",
    filtered["name"].unique()
    )

    lead = filtered[filtered["name"] == selected].iloc[0]
    st.json(lead["score_breakdown"])


st.markdown("---")
st.markdown("Generated by `AI Lead Scoring Pipeline` • Version 1.0")
